### ISSUE TITLE
reductions_helper crashes when trying to reduce the work sizes

### ISSUE THREAD

**Issue by SakalisC** [mpflanzer/clreduce#1]
Hello,

I am having an issue with reducing the work sizes of the input cases. I am running the command as shown here (with output):

```
[chris@chris-Z170X-UD3 ~/clreduce]% python3.5 ./scripts/reduction_helper.py --test-case-dir ./vec100_pre --preprocessed --output vec100_ws --reduce-work-sizes-unchecked
Command: ./scripts/reduction_helper.py --test-case-dir ./vec100_pre --preprocessed --output vec100_ws --reduce-work-sizes-unchecked

CLProg_0.cl Traceback (most recent call last):
  File "./scripts/reduction_helper.py", line 271, in <module>
    options = get_test_options(os.environ)
NameError: name 'get_test_options' is not defined
Runtime: 0 seconds
```

It seems that the function `get_test_options` is part of the `InterestingnessTest` class and its derivatives.

I am using `clreduce` version 92c8e2b

**Comment by mpflanzer** [comment]
Thanks for reporting this. I moved the function recently and must have missed to test the work size reduction afterwards.
I pushed a fix (and tested it). ;-) If you pull the current master branch it should work.

**Comment by SakalisC** [comment]
It works, thank you!
